version: '3.8'

services:
  dev-db:
    image: postgres:latest
    container_name: dev-db
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5434:5432'
    networks:
      - dev-network

  test-db:
    image: postgres:latest
    container_name: test-db
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5435:5432'
    networks:
      - dev-network

networks:
  dev-network:
